// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import io "io"
import mock "github.com/stretchr/testify/mock"

// PadReader is an autogenerated mock type for the PadReader type
type PadReader struct {
	mock.Mock
}

// NewPaddedReader provides a mock function with given fields: r, size
func (_m *PadReader) NewPaddedReader(r io.Reader, size uint64) (io.Reader, uint64) {
	ret := _m.Called(r, size)

	var r0 io.Reader
	if rf, ok := ret.Get(0).(func(io.Reader, uint64) io.Reader); ok {
		r0 = rf(r, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	var r1 uint64
	if rf, ok := ret.Get(1).(func(io.Reader, uint64) uint64); ok {
		r1 = rf(r, size)
	} else {
		r1 = ret.Get(1).(uint64)
	}

	return r0, r1
}

// PaddedSize provides a mock function with given fields: size
func (_m *PadReader) PaddedSize(size uint64) uint64 {
	ret := _m.Called(size)

	var r0 uint64
	if rf, ok := ret.Get(0).(func(uint64) uint64); ok {
		r0 = rf(size)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}
