// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PadReader is an autogenerated mock type for the PadReader type
type PadReader struct {
	mock.Mock
}

// PaddedSize provides a mock function with given fields: size
func (_m *PadReader) PaddedSize(size uint64) uint64 {
	ret := _m.Called(size)

	var r0 uint64
	if rf, ok := ret.Get(0).(func(uint64) uint64); ok {
		r0 = rf(size)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}
