stateDiagram-v2
	state "DealStatusNew" as 0
	state "DealStatusUnsealing" as 1
	state "DealStatusUnsealed" as 2
	state "DealStatusFailed" as 9
	state "DealStatusFundsNeeded" as 11
	state "DealStatusOngoing" as 14
	state "DealStatusFundsNeededLastPayment" as 15
	state "DealStatusCompleted" as 16
	state "DealStatusErrored" as 19
	state "DealStatusBlocksComplete" as 20
	state "DealStatusFinalizing" as 21
	1 : On entry runs UnsealData
	2 : On entry runs UnpauseDeal
	9 : On entry runs CancelDeal
	[*] --> 0
	note right of 0
		The following events are not shown cause they can trigger from any state.

		ProviderEventDataTransferError - transitions state to DealStatusErrored
	end note
	0 --> 0 : ProviderEventOpen
	0 --> 1 : ProviderEventDealAccepted
	1 --> 9 : ProviderEventUnsealError
	1 --> 2 : ProviderEventUnsealComplete
	2 --> 14 : ProviderEventUnpauseDeal
	14 --> 14 : ProviderEventBlockReceived
	14 --> 20 : ProviderEventBlocksCompleted
	14 --> 11 : ProviderEventPaymentRequested
	20 --> 15 : ProviderEventPaymentRequested
	11 --> 9 : ProviderEventSaveVoucherFailed
	15 --> 9 : ProviderEventSaveVoucherFailed
	11 --> 11 : ProviderEventPartialPaymentReceived
	15 --> 15 : ProviderEventPartialPaymentReceived
	11 --> 14 : ProviderEventPaymentReceived
	15 --> 21 : ProviderEventPaymentReceived
	21 --> 16 : ProviderEventComplete
