stateDiagram-v2
	state "DealStatusNew" as 0
	state "DealStatusWaitForAcceptance" as 3
	state "DealStatusPaymentChannelCreating" as 4
	state "DealStatusPaymentChannelAddingFunds" as 5
	state "DealStatusPaymentChannelReady" as 6
	state "DealStatusAccepted" as 8
	state "DealStatusFailed" as 9
	state "DealStatusRejected" as 10
	state "DealStatusFundsNeeded" as 11
	state "DealStatusSendFunds" as 12
	state "DealStatusSendFundsLastPayment" as 13
	state "DealStatusOngoing" as 14
	state "DealStatusFundsNeededLastPayment" as 15
	state "DealStatusCompleted" as 16
	state "DealStatusDealNotFound" as 17
	state "DealStatusErrored" as 19
	state "DealStatusBlocksComplete" as 20
	state "DealStatusFinalizing" as 21
	0 : On entry runs ProposeDeal
	4 : On entry runs WaitForPaymentChannelCreate
	5 : On entry runs WaitForPaymentChannelAddFunds
	6 : On entry runs UnpauseDeal
	8 : On entry runs SetupPaymentChannelStart
	9 : On entry runs CancelDeal
	11 : On entry runs ProcessPaymentRequested
	12 : On entry runs SendFunds
	13 : On entry runs SendFunds
	14 : On entry runs Ongoing
	15 : On entry runs ProcessPaymentRequested
	[*] --> 0
	note right of 0
		The following events are not shown cause they can trigger from any state.

		ClientEventWriteDealProposalErrored - transitions state to DealStatusErrored
		ClientEventUnknownResponseReceived - transitions state to DealStatusFailed
		ClientEventDataTransferError - transitions state to DealStatusErrored
		ClientEventWriteDealPaymentErrored - transitions state to DealStatusErrored
	end note
	0 --> 0 : ClientEventOpen
	0 --> 3 : ClientEventDealProposed
	3 --> 10 : ClientEventDealRejected
	3 --> 17 : ClientEventDealNotFound
	3 --> 8 : ClientEventDealAccepted
	4 --> 9 : ClientEventPaymentChannelErrored
	8 --> 9 : ClientEventPaymentChannelErrored
	8 --> 4 : ClientEventPaymentChannelCreateInitiated
	8 --> 5 : ClientEventPaymentChannelAddingFunds
	4 --> 6 : ClientEventPaymentChannelReady
	5 --> 6 : ClientEventPaymentChannelReady
	4 --> 9 : ClientEventAllocateLaneErrored
	5 --> 9 : ClientEventAllocateLaneErrored
	5 --> 9 : ClientEventPaymentChannelAddFundsErrored
	6 --> 14 : ClientEventUnpauseDeal
	11 --> 15 : ClientEventLastPaymentRequested
	14 --> 15 : ClientEventLastPaymentRequested
	15 --> 15 : ClientEventLastPaymentRequested
	20 --> 13 : ClientEventLastPaymentRequested
	11 --> 11 : ClientEventPaymentRequested
	14 --> 11 : ClientEventPaymentRequested
	14 --> 20 : ClientEventAllBlocksReceived
	15 --> 13 : ClientEventAllBlocksReceived
	20 --> 20 : ClientEventAllBlocksReceived
	11 --> 11 : ClientEventBlocksReceived
	14 --> 14 : ClientEventBlocksReceived
	15 --> 15 : ClientEventBlocksReceived
	11 --> 12 : ClientEventSendFunds
	15 --> 13 : ClientEventSendFunds
	13 --> 9 : ClientEventFundsExpended
	11 --> 9 : ClientEventBadPaymentRequested
	13 --> 9 : ClientEventBadPaymentRequested
	12 --> 9 : ClientEventCreateVoucherFailed
	13 --> 9 : ClientEventCreateVoucherFailed
	12 --> 14 : ClientEventPaymentSent
	13 --> 21 : ClientEventPaymentSent
	21 --> 16 : ClientEventComplete
	9 --> 19 : <invalid Value>

	note left of 4 : The following events only record in this state.<br><br>ClientEventLastPaymentRequested<br>ClientEventPaymentRequested<br>ClientEventAllBlocksReceived<br>ClientEventBlocksReceived


	note left of 5 : The following events only record in this state.<br><br>ClientEventLastPaymentRequested<br>ClientEventPaymentRequested<br>ClientEventAllBlocksReceived<br>ClientEventBlocksReceived


	note left of 6 : The following events only record in this state.<br><br>ClientEventLastPaymentRequested<br>ClientEventPaymentRequested<br>ClientEventAllBlocksReceived<br>ClientEventBlocksReceived


	note left of 8 : The following events only record in this state.<br><br>ClientEventLastPaymentRequested<br>ClientEventPaymentRequested<br>ClientEventAllBlocksReceived<br>ClientEventBlocksReceived

