stateDiagram-v2
	state "DealStatusNew" as 0
	state "DealStatusWaitForAcceptance" as 3
	state "DealStatusPaymentChannelCreating" as 4
	state "DealStatusPaymentChannelAddingFunds" as 5
	state "DealStatusAccepted" as 6
	state "DealStatusFailed" as 7
	state "DealStatusRejected" as 8
	state "DealStatusFundsNeeded" as 9
	state "DealStatusSendFunds" as 10
	state "DealStatusSendFundsLastPayment" as 11
	state "DealStatusOngoing" as 12
	state "DealStatusFundsNeededLastPayment" as 13
	state "DealStatusCompleted" as 14
	state "DealStatusDealNotFound" as 15
	state "DealStatusErrored" as 16
	state "DealStatusBlocksComplete" as 17
	state "DealStatusFinalizing" as 18
	0 : On entry runs ProposeDeal
	4 : On entry runs WaitForPaymentChannelCreate
	5 : On entry runs WaitForPaymentChannelAddFunds
	6 : On entry runs SetupPaymentChannelStart
	7 : On entry runs CancelDeal
	9 : On entry runs ProcessPaymentRequested
	10 : On entry runs SendFunds
	11 : On entry runs SendFunds
	12 : On entry runs Ongoing
	13 : On entry runs ProcessPaymentRequested
	[*] --> 0
	note right of 0
		The following events are not shown cause they can trigger from any state.

		ClientEventWriteDealProposalErrored - transitions state to DealStatusErrored
		ClientEventUnknownResponseReceived - transitions state to DealStatusFailed
		ClientEventDataTransferError - transitions state to DealStatusErrored
		ClientEventWriteDealPaymentErrored - transitions state to DealStatusErrored
	end note
	0 --> 0 : ClientEventOpen
	0 --> 3 : ClientEventDealProposed
	3 --> 8 : ClientEventDealRejected
	3 --> 15 : ClientEventDealNotFound
	3 --> 6 : ClientEventDealAccepted
	4 --> 7 : ClientEventPaymentChannelErrored
	6 --> 7 : ClientEventPaymentChannelErrored
	6 --> 4 : ClientEventPaymentChannelCreateInitiated
	6 --> 5 : ClientEventPaymentChannelAddingFunds
	4 --> 12 : ClientEventPaymentChannelReady
	5 --> 12 : ClientEventPaymentChannelReady
	4 --> 7 : ClientEventAllocateLaneErrored
	5 --> 7 : ClientEventAllocateLaneErrored
	5 --> 7 : ClientEventPaymentChannelAddFundsErrored
	9 --> 13 : ClientEventLastPaymentRequested
	12 --> 13 : ClientEventLastPaymentRequested
	13 --> 13 : ClientEventLastPaymentRequested
	17 --> 11 : ClientEventLastPaymentRequested
	9 --> 9 : ClientEventPaymentRequested
	12 --> 9 : ClientEventPaymentRequested
	17 --> 9 : ClientEventPaymentRequested
	12 --> 17 : ClientEventAllBlocksReceived
	13 --> 11 : ClientEventAllBlocksReceived
	17 --> 17 : ClientEventAllBlocksReceived
	9 --> 9 : ClientEventBlocksReceived
	12 --> 12 : ClientEventBlocksReceived
	13 --> 13 : ClientEventBlocksReceived
	9 --> 10 : ClientEventSendFunds
	13 --> 11 : ClientEventSendFunds
	10 --> 7 : ClientEventFundsExpended
	11 --> 7 : ClientEventFundsExpended
	10 --> 7 : ClientEventBadPaymentRequested
	11 --> 7 : ClientEventBadPaymentRequested
	10 --> 7 : ClientEventCreateVoucherFailed
	11 --> 7 : ClientEventCreateVoucherFailed
	10 --> 12 : ClientEventPaymentSent
	11 --> 18 : ClientEventPaymentSent
	18 --> 14 : ClientEventComplete
	7 --> 16 : <invalid Value>

	note left of 3 : The following events only record in this state.<br><br>ClientEventLastPaymentRequested<br>ClientEventPaymentRequested<br>ClientEventAllBlocksReceived<br>ClientEventBlocksReceived


	note left of 4 : The following events only record in this state.<br><br>ClientEventLastPaymentRequested<br>ClientEventPaymentRequested<br>ClientEventAllBlocksReceived<br>ClientEventBlocksReceived


	note left of 5 : The following events only record in this state.<br><br>ClientEventLastPaymentRequested<br>ClientEventPaymentRequested<br>ClientEventAllBlocksReceived<br>ClientEventBlocksReceived


	note left of 6 : The following events only record in this state.<br><br>ClientEventLastPaymentRequested<br>ClientEventPaymentRequested<br>ClientEventAllBlocksReceived<br>ClientEventBlocksReceived

