stateDiagram-v2
	state "StorageDealUnknown" as 0
	state "StorageDealStaged" as 4
	state "StorageDealSealing" as 5
	state "StorageDealActive" as 6
	state "StorageDealRejecting" as 9
	state "StorageDealFailing" as 10
	state "StorageDealValidating" as 13
	state "StorageDealAcceptWait" as 14
	state "StorageDealTransferring" as 16
	state "StorageDealWaitingForData" as 17
	state "StorageDealVerifyData" as 18
	state "StorageDealEnsureProviderFunds" as 19
	state "StorageDealProviderFunding" as 21
	state "StorageDealPublish" as 23
	state "StorageDealPublishing" as 24
	state "StorageDealError" as 25
	state "StorageDealCompleted" as 26
	4 : On entry runs HandoffDeal
	5 : On entry runs VerifyDealActivated
	6 : On entry runs RecordPieceInfo
	9 : On entry runs RejectDeal
	10 : On entry runs FailDeal
	13 : On entry runs ValidateDealProposal
	14 : On entry runs DecideOnProposal
	18 : On entry runs VerifyData
	19 : On entry runs EnsureProviderFunds
	21 : On entry runs WaitForFunding
	23 : On entry runs PublishDeal
	24 : On entry runs WaitForPublish
	[*] --> 0
	note right of 0
		The following events are not shown cause they can trigger from any state.

		ProviderEventNodeErrored - transitions state to StorageDealFailing
		ProviderEventRestart - does not transition state
	end note
	0 --> 13 : ProviderEventOpen
	13 --> 9 : ProviderEventDealRejected
	14 --> 9 : ProviderEventDealRejected
	18 --> 9 : ProviderEventDealRejected
	9 --> 10 : ProviderEventRejectionSent
	13 --> 14 : ProviderEventDealDeciding
	14 --> 17 : ProviderEventDataRequested
	16 --> 10 : ProviderEventDataTransferFailed
	17 --> 16 : ProviderEventDataTransferInitiated
	16 --> 18 : ProviderEventDataTransferCompleted
	18 --> 10 : ProviderEventDataVerificationFailed
	17 --> 19 : ProviderEventVerifiedData
	18 --> 19 : ProviderEventVerifiedData
	19 --> 21 : ProviderEventFundingInitiated
	19 --> 23 : ProviderEventFunded
	21 --> 23 : ProviderEventFunded
	23 --> 24 : ProviderEventDealPublishInitiated
	24 --> 10 : ProviderEventDealPublishError
	9 --> 10 : ProviderEventSendResponseFailed
	14 --> 10 : ProviderEventSendResponseFailed
	24 --> 4 : ProviderEventDealPublished
	4 --> 10 : ProviderEventFileStoreErrored
	5 --> 10 : ProviderEventFileStoreErrored
	6 --> 10 : ProviderEventFileStoreErrored
	4 --> 10 : ProviderEventDealHandoffFailed
	4 --> 5 : ProviderEventDealHandedOff
	5 --> 10 : ProviderEventDealActivationFailed
	5 --> 6 : ProviderEventDealActivated
	6 --> 10 : ProviderEventPieceStoreErrored
	6 --> 26 : ProviderEventDealCompleted
	6 --> 10 : ProviderEventUnableToLocatePiece
	6 --> 10 : ProviderEventReadMetadataErrored
	10 --> 25 : ProviderEventFailed
	9 --> 25 : ProviderEventRestart
	13 --> 25 : ProviderEventRestart
	14 --> 25 : ProviderEventRestart
	25 --> [*]
	26 --> [*]
